### ISSUE TITLE
求助！如何从公钥私钥对生成 `sm2.PrivateKey` ？

### ISSUE THREAD

**Issue by stonemax** [tjfoc/gmsm#100]
我们开发使用了别人分配的公钥（04开头的130位字符串）、私钥对（64位字符串），现在需要使用 `sm2.PrivateKey.Sign` 方法对数据进行签名，可是实在不知道如何生成 `sm2.PrivateKey` 实例。

在 issue 中找到了 [如何从字符串中读取公钥私钥](https://github.com/tjfoc/gmsm/issues/77) 这篇文章，但是其并未说明如何生成私钥实例，还请各位大神协助。

**Comment by hundan2020** [comment]
```
priv, err := sm2.GenerateKey(nil)
```

see <https://github.com/tjfoc/gmsm/blob/master/API%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md#%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B>

**Comment by stonemax** [comment]
> ```
> priv, err := sm2.GenerateKey(nil)
> ```
> 
> see https://github.com/tjfoc/gmsm/blob/master/API%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md#%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B
> 
> or maybe this help
> 
> ```go
> 	d,_:=ioutil.ReadFile("pri.key")
> 	x,_:=ioutil.ReadFile("pub.x.key")
> 	y,_:=ioutil.ReadFile("pub.y.key")
> 	//bb:=bytes.NewReader(r)
> 	xx:=new(big.Int).SetBytes(x)
> 	yy:=new(big.Int).SetBytes(y)
> 	dd:=new(big.Int).SetBytes(d)
> 	priv := sm2.PrivateKey{
> 		PublicKey: sm2.PublicKey{
> 			Curve: sm2.P256Sm2(),
> 			X: xx,
> 			Y: yy,
> 		},
> 		D: dd,
> 	}
> ```
> 
> or this
> 
> https://github.com/tjfoc/gmsm/blob/master/x509/x509_test.go

I have resolved this issue, but still thank you @hundan2020  anyway. In my case, the private/public key is represented as string, such as:
* private-key: 07e4********;
* public-key: 047c********.

Restore SM2 public key from string:

```go
func generateSM2PublicKey(publicKeyStr string) *sm2.PublicKey {
	publicKeyStr = strings.TrimLeft(strings.TrimPrefix(publicKeyStr, "04"), "0")

	x, _ := new(big.Int).SetString(publicKeyStr[0:64], 16)
	y, _ := new(big.Int).SetString(publicKeyStr[64:], 16)

	return &sm2.PublicKey{
		Curve: sm2.P256Sm2(),
		X:     x,
		Y:     y,
	}
}
```

Restore SM2 keys from string:

```go
func generateSM2Keys(privateKeyStr, publicKeyStr string) (*sm2.PublicKey, *sm2.PrivateKey) {
	publicKey := generateSM2PublicKey(publicKeyStr)

	privateKeyStr = strings.TrimLeft(privateKeyStr, "0")
	d, _ := new(big.Int).SetString(privateKeyStr[:], 16)

	privateKey := &sm2.PrivateKey{
		PublicKey: *publicKey,
		D:         d,
	}

	return publicKey, privateKey
}
```
