### ISSUE TITLE
why remove func Sign(priv *PrivateKey, hash []byte) (r, s *big.Int, err error) from sm2.go?

### ISSUE THREAD

**Issue by fffmonkeyking** [tjfoc/gmsm#101]
why remove func Sign(priv *PrivateKey, hash []byte) (r, s *big.Int, err error) from sm2.go ?

**Comment by czdsdo** [comment]
v1.0.0 版本是基于Go的标准库ECC实现修改的， sign方法使用sha512哈希算法，是不符合sm2标准要求的，应使用sm3哈希实现。为了兼容加密机等旧签名验签实现，增加了Verify(pub *PublicKey, hash []byte, r, s *big.Int)实现。hash也需要严格按照Sm3Digest（）方法实现。
严格来说，现在sign方法中的msg参数就是原先方法中的hash参数。在原参数中要求加入了新参数uid。
