### ISSUE TITLE
sm4中的IV为什么不需要随机生成？

### ISSUE THREAD

**Issue by tututt** [tjfoc/gmsm#102]

**Comment by czdsdo** [comment]
加密解密时IV值要统一，否则会解密失败。为了使用方法由于就默认取0值了。

**Comment by tututt** [comment]
那其实可以外部传入是不是，这样安全性更高

**Comment by czdsdo** [comment]
是的，由于会多加一个传入参数，考虑到兼容性，与其他库互操作时也没要求自定义IV值，所以就暂时没把IV暴露出来。

**Comment by tututt** [comment]
这块有后续的计划吗，因为iv固定的话实际和ECB模式没有差别了

**Comment by czdsdo** [comment]
其他模式里的设置的IV值会影响到第一次分组的结果，后续分组操作会基于上次操作的结果。IV值的设置与否不会影响各种模式的操作逻辑流程。

**Comment by tututt** [comment]
不好意思，是我看差了，确实有影响，后续暴露IV的计划吗？

**Comment by czdsdo** [comment]
下个版本会暴露， 预计下个月。

**Comment by tututt** [comment]
好的，感谢回答，我close了

**Comment by cocosip** [comment]
这都多少年了，这个IV还没暴露出来？

**Comment by czdsdo** [comment]
SetIV()方法设置IV值

**Comment by cocosip** [comment]
按照你现在的结构，你如何支持并发？
