### ISSUE TITLE
v1.4.0版本不能向下兼容的问题

### ISSUE THREAD

**Issue by thisjok** [tjfoc/gmsm#103]
对于目录sm2中的sm2.go文件，Sign函数的定义如下(不同版本)：
`v1.4.0:
没有单独定义：Sign function
`
`v1.3.1:
func Sign(priv *PrivateKey, hash []byte) (r, s *big.Int, err error)
`
可以看到v1.4.0删除了对Sign的定义，从而引入版本不能向下兼容的问题;
为了解决这个问题，有多种途径供参考：

- 增加v1.4.0中对Sign的定义，使之和v1.3.1保持一致;（当然我不清楚是否还有其他地方存在向下不兼容的情况，这里假设只有这一处）
- 根据语义化版本2.0.0的规范，修改v1.4.0版本号为其他版本号，example: v2.0.0;
- 其他更好的方法;

FYI

**Comment by czdsdo** [comment]
后续解决方法为修改版本号.发布版本时当时没考虑到规范。目前1.4.0版本为了兼容更大众的使用要求，有不少破坏性更新，不能向下兼容

**Comment by czdsdo** [comment]
发布2.0.0版本

**Comment by thisjok** [comment]
Got it, thanks for your work!
