### ISSUE TITLE
Convert keypair to hex

### ISSUE THREAD

**Issue by pedroalbanese** [tjfoc/gmsm#105]
Hi,

I'm trying to reproduce the asymmetric cryptography example, but I don't understand how to save the keys. I can't convert them to hexadecimal.

How do I convert keys to hexadecimal (preferably) or plain text like Base64 / Pem, etc.

I can't convert *sm2.PublicKey to []bytes. (I'm new to the Go language)

Thanks in advance.

**Comment by czdsdo** [comment]
pem: x509_test.go, x509/utils.go 
```
pubkeyPem, err:=x509.WritePublicKeyToPem(pubKey)
 ioutil.WriteFile("pub.pem",pubkeyPem,0644)
```

 

hexadecimal :sm2/utils.go

```
pubBytes:=Compress(pub)  
pub=Decompress(pubBytes)
hex.EncodeToString(pubBytes)
```

**Comment by pedroalbanese** [comment]
Sorry, but cannot understand? Is an example like this possible?

<pre>
func SignatureRSA(sourceData []byte) ([]byte, error) {
	msg := []byte("")
	file, err := os.Open(*key)
	if err != nil {
		return msg, err
	}
	info, err := file.Stat()
	if err != nil {
		return msg, err
	}
	buf := make([]byte, info.Size())
	file.Read(buf)
	block, _ := pem.Decode(buf)
	privateKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		return msg, err
	}
	myHash := sha256.New()
	myHash.Write(sourceData)
	hashRes := myHash.Sum(nil)
	res, err := rsa.SignPKCS1v15(rand.Reader, privateKey, crypto.SHA256, hashRes)
	if err != nil {
		return msg, err
	}
	defer file.Close()
	return res, nil
}

func VerifyRSA(sourceData, signedData []byte) error {
	file, err := os.Open(*key)
	if err != nil {
		return err
	}
	info, err := file.Stat()
	if err != nil {
		return err
	}
	buf := make([]byte, info.Size())
	file.Read(buf)
	block, _ := pem.Decode(buf)
	publicInterface, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return err
	}
	publicKey := publicInterface.(*rsa.PublicKey)
	mySha := sha256.New()
	mySha.Write(sourceData)
	res := mySha.Sum(nil)

	err = rsa.VerifyPKCS1v15(publicKey, crypto.SHA256, res, signedData)
	if err != nil {
		return err
	}
	defer file.Close()
	return nil
}

func GenerateRsaKey(bit int) error {
	private, err := rsa.GenerateKey(rand.Reader, bit)
	if err != nil {
		return err
	}
	privateStream := x509.MarshalPKCS1PrivateKey(private)
	block := pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: privateStream,
	}
	file, err := os.Create("private" + *suf)
	if err != nil {
		return err
	}
	err = pem.Encode(file, &block)
	if err != nil {
		return err
	}
	public := private.PublicKey
	publicStream, err := x509.MarshalPKIXPublicKey(&public)
	if err != nil {
		return err
	}
	pubblock := pem.Block{Type: "RSA PUBLIC KEY", Bytes: publicStream,}
	pubfile, err := os.Create("public" + *suf)
	if err != nil {
		return err
	}
	err = pem.Encode(pubfile, &pubblock)
	if err != nil {
		return err
	}
	return nil

}
</pre>

Thanks!

**Comment by czdsdo** [comment]
pem: x509_test.go, x509/utils.go 
```
func WritePubToPemFile(file string,pubKey *sm2.PublicKey){
pubkeyPem, err:=x509.WritePublicKeyToPem(pubKey,nil)
 ioutil.WriteFile(file,pubkeyPem,0644)  
}
```
```
func ReadPubFromPemFile(file string)( *sm2.PublicKey,error){
pubkeyPem:= ioutil.ReadFile(file)  
pubkey, err:=x509.ReadPrivateKeyFromPem(pubkeyPem,nil)
return pubkey,err
}
 
```
hexadecimal :sm2/utils.go

```
func convertPubTohex(pub *sm2.PublicKey) string{
pubBytes:=Compress(pub)  
pub=Decompress(pubBytes)
return hex.EncodeToString(pubBytes)
}
```

or x509/utils.go
```
ReadPrivateKeyFromHex(Dhex string)
WritePrivateKeyToHex(key *sm2.PrivateKey)
ReadPublicKeyFromHex(Qhex string) 
WritePublicKeyToHex(key *sm2.PublicKey) string
```

**Comment by pedroalbanese** [comment]
It worked:
```go
func convertPubTohex(pub *sm2.PublicKey) string{
	pubBytes:=sm2.Compress(pub)  
	pub=sm2.Decompress(pubBytes)
	return hex.EncodeToString(pubBytes)
}
```
But it don't work:
```go
func convertPriTohex(priv *sm2.PrivateKey) string{
	priBytes:=sm2.Compress(priv)  
	priv=sm2.Decompress(priBytes)
	return hex.EncodeToString(priBytes)
}
```
I need a command that generates the key pair and another that encrypts and decrypts with the given keys. 

Apologies for the delay. Thank You!

**Comment by czdsdo** [comment]
` x509/utils.go`
`
//DHex是sm2私钥的真正关键数值
func ReadPrivateKeyFromHex(Dhex string) (*sm2.PrivateKey,error) {
	c := sm2.P256Sm2()
	d,err:=hex.DecodeString(Dhex)
	if err!=nil{
		return nil,err
	}
	k:= new(big.Int).SetBytes(d)
	params := c.Params()
	one := new(big.Int).SetInt64(1)
	n := new(big.Int).Sub(params.N, one)
	if k.Cmp(n)>=0{
      return nil,errors.New("privateKey's D is overflow.")
	}
	priv := new(sm2.PrivateKey)
	priv.PublicKey.Curve = c
	priv.D = k
	priv.PublicKey.X, priv.PublicKey.Y = c.ScalarBaseMult(k.Bytes())
	return priv,nil
}



func WritePrivateKeyToHex(key *sm2.PrivateKey) string {
	return key.D.Text(16)
}

func ReadPublicKeyFromHex(Qhex string) (*sm2.PublicKey, error) {
	q,err:=hex.DecodeString(Qhex)
	if err!=nil{
		return nil,err
	}
	if len(q)==65&&q[0]==byte(0x04){
		q=q[1:]
	}
	if len(q)!=64{
		return nil,errors.New("publicKey is not uncompressed.")
	}
	pub := new(sm2.PublicKey)
	pub.Curve = sm2.P256Sm2()
	pub.X = new(big.Int).SetBytes(q[:32])
	pub.Y = new(big.Int).SetBytes(q[32:])
	return pub, nil
}


func WritePublicKeyToHex(key *sm2.PublicKey) string {
	x := key.X.Bytes()
	y := key.Y.Bytes()
	if n := len(x); n < 32 {
		x = append(zeroByteSlice()[:32-n], x...)
	}
	if n := len(y); n < 32 {
		y = append(zeroByteSlice()[:32-n], y...)
	}
	c := []byte{}
	c = append(c, x...)
	c = append(c, y...)
	c = append([]byte{0x04}, c...)
	return hex.EncodeToString(c)
}`

**Comment by pedroalbanese** [comment]
Error:

.\utils.go:58:12: undefined: zeroByteSlice

**Comment by pedroalbanese** [comment]
I made this test script, it's working to encrypt but not to decrypt:

```go
package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"github.com/tjfoc/gmsm/sm2"
	"log"
)

var (
	gen = flag.Bool("keygen", false, "Generate asymmetric key pair.")
	enc = flag.Bool("enc", false, "Encrypt with Publickey.")
	dec = flag.Bool("dec", false, "Decrypt with PrivateKey.")
	key = flag.String("key", "", "Private/Public key.")
	str = flag.String("str", "", "String to Encrypt/Decrypt.")
)

func main() {
	flag.Parse()

	if *gen == true {
		priv, err := sm2.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		pub := &priv.PublicKey

		fmt.Println("Private= " + WritePrivateKeyToHex(priv))
		fmt.Println("Public= " + WritePublicKeyToHex(pub))
	}

	if *enc {
		pub, err := ReadPublicKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		ciphertxt, err := pub.EncryptAsn1([]byte(*str), rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("Ciphered:%x\n", ciphertxt)
	}

	if *dec {
		priv, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		plaintxt, err := priv.DecryptAsn1([]byte(*str))
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("Deciphered:%s\n", string(plaintxt))
	}
}
```

Decryption I'm getting error:

2021/06/24 10:43:03 asn1: structure error: tags don't match (16 vs {class:0 tag:19 length:48 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} sm2Cipher @2

Thanks!

**Comment by czdsdo** [comment]
use  ciphertxt   to DecryptAsn1   ..`plaintxt, err := priv.DecryptAsn1([]byte(ciphertxt))`

**Comment by pedroalbanese** [comment]
But for that I would have to encrypt the text. Assuming I don't know what the plaintext is, I only need to pass the ciphertext to decrypt with the private key.. Looks like ciphertext is in hex, would I have to convert it to binary?

**Comment by pedroalbanese** [comment]
I don't understand how to decrypt content encrypted by another process, on the remote side for example..

It also bugs:

```go
package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"github.com/tjfoc/gmsm/sm2"
	"log"
)

var (
	gen = flag.Bool("keygen", false, "Generate asymmetric key pair.")
	enc = flag.Bool("enc", false, "Encrypt with Publickey.")
	dec = flag.Bool("dec", false, "Decrypt with PrivateKey.")
	key = flag.String("key", "", "Private/Public key.")
	str = flag.String("str", "", "String to Encrypt/Decrypt.")
)

func main() {
	flag.Parse()

	if *gen == true {
		priv, err := sm2.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		pub := &priv.PublicKey

		fmt.Println("Private= " + WritePrivateKeyToHex(priv))
		fmt.Println("Public= " + WritePublicKeyToHex(pub))
	}

	if *enc {
		pub, err := ReadPublicKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}

		ciphertxt, err := sm2.Encrypt(pub, []byte(*str), rand.Reader, 1)
		if err != nil {
			fmt.Printf("Error: failed to encrypt %s: %v\n", []byte(*str), err)
			return
		}

		fmt.Printf("Ciphered:%x\n", ciphertxt)
	}

	if *dec {
		priv, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}

		plaintxt, err := sm2.Decrypt(priv, []byte(*str), 1)
		if err != nil {
			fmt.Printf("Error: failed to decrypt: %v\n", err)
		}
		fmt.Printf("Deciphered:%s\n", string(plaintxt))
	}
}
```

**Comment by pedroalbanese** [comment]
Now works fine. Thank You very much !!

package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"encoding/hex"
	"github.com/tjfoc/gmsm/sm2"
	"log"
)

var (
	gen = flag.Bool("keygen", false, "Generate asymmetric key pair.")
	enc = flag.Bool("enc", false, "Encrypt with Publickey.")
	dec = flag.Bool("dec", false, "Decrypt with PrivateKey.")
	key = flag.String("key", "", "Private/Public key.")
	str = flag.String("str", "", "String to Encrypt/Decrypt.")
)

func main() {
	flag.Parse()

	if *gen == true {
		priv, err := sm2.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		pub := &priv.PublicKey

		fmt.Println("Private= " + WritePrivateKeyToHex(priv))
		fmt.Println("Public= " + WritePublicKeyToHex(pub))
	}

	if *enc {
		pub, err := ReadPublicKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		ciphertxt, err := pub.EncryptAsn1([]byte(*str), rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("Ciphered:%x\n", ciphertxt)
	}

	if *dec {
		priv, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		str, _ := hex.DecodeString(*str)
		plaintxt, err := priv.DecryptAsn1([]byte(str))
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("Deciphered:%s\n", plaintxt)
	}
}
