### ISSUE TITLE
About the  elliptic curve  used in SM2

### ISSUE THREAD

**Issue by poundscaoying** [tjfoc/gmsm#12]
IS the curve used in Go pkg (elliptic) which is y2 = x3 - 3x +b satisfied with National Standard ?

**Comment by tjfoc** [comment]
SM2 standard should be y^2 = x ^3 +ax + b

**Comment by poundscaoying** [comment]
Thanks for reply.I'm so sorry that  I just find there are only five parameters in your new p256.go, but without the parameter a in y2=X3+ax+b.And unfortunately,the parameter a should be  -3 in the original elliptic pkg.According to the SM2 stabard,this parameter should be greater equal to 0(when the based field is Fp).

**Comment by poundscaoying** [comment]
Actually,maybe there is a need for new ScalarMult function in elliptic.go.

**Comment by tjfoc** [comment]
actually we are using the same elliptic curve as national standard.

**Comment by poundscaoying** [comment]
Would you mind telling me the elliptic curve you have used in your sm2？Thank you anyway.

**Comment by tjfoc** [comment]
same as  y^2 = x ^3 +ax + b
