### ISSUE TITLE
Correct way to perform Shared Key Agreement

### ISSUE THREAD

**Issue by pedroalbanese** [tjfoc/gmsm#123]
Greetings!!

Is this correct or it's insecure?

```go
	private, err := ReadPrivateKeyFromHex(*key)
	if err != nil {
		log.Fatal(err)
	}
	public, err := ReadPublicKeyFromHex(*public)
	if err != nil {
		log.Fatal(err)
	}

	b, _ := public.Curve.ScalarMult(public.X, public.Y, private.D.Bytes())
	shared := sm3.Sm3Sum(b.Bytes())
	fmt.Printf("Shared= %x\n",  shared)
```

Thanks in advance!

**Comment by czdsdo** [comment]
This is an implementation of some other elliptic curve.
Generating shared key need follow the sm2 standard.
use sm2.keyExchange() to generate shared Key.

**Comment by pedroalbanese** [comment]
Right, but I can't understand it:
"want (int, []byte, []byte, *sm2.PrivateKey, *sm2.PublicKey, *sm2.PrivateKey, *sm2.PublicKey, bool)"

What's that []bytes? and why two keypair? Since the other party's private key is secret, I need to perform the operation having access only to the other party's public key and my private key. I need to perform this operation having access to only two keys.

If you have a tip on how to do this in a single-line script it would be very welcome.

**Comment by czdsdo** [comment]
Referring to  sm2/sm2_test.go   TestKEB2()
 That []bytes are users' identification, It is usually represented by  user's name.
da and db are users' key.
Key sharing  requires random numbers.
ra and rb are users' random key.

**Comment by pedroalbanese** [comment]
But how to put it in a single line as:
b, _, _, err := sm2.keyExchange(int(16), []byte(""), []byte(""), private, public, private, public, false)

Thanks!

**Comment by czdsdo** [comment]
use KeyExchangeA and KeyExchangeB instead of keyExchange.
The two users need to communicate and send  some information .
userA need to send publicA  and randompublicA  to userB.
userA need to send publicB and randompublicB  to userA.
Then both side  exchange  Sb, S2 and S1, Sa.
if  Sb==S1 and S2==Sa, then it is successfull.

**Comment by pedroalbanese** [comment]
Pardon my ignorance but I can't call the functions:

.\main.go:134:19: cannot refer to unexported name sm2.keyExchangeA
.\main.go:134:19: undefined: sm2.keyExchangeA

How to call the function?

**Comment by pedroalbanese** [comment]
It worked:

```go
		private, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		public, err := ReadPublicKeyFromHex(*pub)
		if err != nil {
			log.Fatal(err)
		}

		ra := []byte(*ra)
		rb := []byte(*rb)

		a, S1, Sa, err := sm2.KeyExchangeA(32, ra, rb, private, public, private, public)
		b, Sb, S2, err := sm2.KeyExchangeB(32, ra, rb, private, public, private, public)
		fmt.Printf("SharedB= %x\n\n",  b)
		fmt.Printf("S1= %x\n",  S1)
		fmt.Printf("Sb= %x\n\n",  Sb)
		fmt.Printf("SharedA= %x\n\n",  a)
		fmt.Printf("Sa= %x\n",  Sa)
		fmt.Printf("S2= %x\n\n",  S2)
```

But I didn't quite understand how it works. It performs secret key derivation in reverse order, it means one party will always have to use sm2.KeyExchangeA and the other party sm2.KeyExchangeB and one function is useless without the other. I still don't understand why it asks for two private keys.

Even if they are in different roles, I should only provide one private and one public key in each one. Otherwise I don't understand how to make the client application. Both functions require two pairs of keys to work correctly. I mean, in the example above, I have to enter the same variables twice that it's a single key pair and receive two secret keys in different order for each side.

**Comment by pedroalbanese** [comment]
Is this example correct?

```go
package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/tjfoc/gmsm/sm2"
)

var (
	gen = flag.Bool("gen", false, "Generate asymmetric key pair.")
	key = flag.String("key", "", "Private/Public key.")
	drv = flag.String("drv", "", "Derive shared secret [A|B].")
	pub = flag.String("pub", "", "Remote's side Publickey.")
	ra  = flag.String("ra", "", "RandomPublicA.")
	rb  = flag.String("rb", "", "RandomPublicB.")
)

func main() {
	flag.Parse()

	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage of", os.Args[0]+":")
		flag.PrintDefaults()
		os.Exit(0)
	}

	if *gen == true {
		priv, err := sm2.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		pub := &priv.PublicKey

		fmt.Println("Private= " + WritePrivateKeyToHex(priv))
		fmt.Println("Public= " + WritePublicKeyToHex(pub))
	}

	if *drv == "a" {
		private, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		public, err := ReadPublicKeyFromHex(*pub)
		if err != nil {
			log.Fatal(err)
		}

		ra := []byte(*ra)
		rb := []byte(*rb)

		k1, S1, Sa, err := sm2.KeyExchangeA(16, ra, rb, private, public, private, public)

		fmt.Printf("K1= %x\n",  k1)
		fmt.Printf("S1= %x\n",  S1)
		fmt.Printf("Sa= %x\n\n",  Sa)

	}
	if *drv == "b" {
		private, err := ReadPrivateKeyFromHex(*key)
		if err != nil {
			log.Fatal(err)
		}
		public, err := ReadPublicKeyFromHex(*pub)
		if err != nil {
			log.Fatal(err)
		}

		ra := []byte(*ra)
		rb := []byte(*rb)

		k2, Sb, S2, err := sm2.KeyExchangeB(16, ra, rb, private, public, private, public)
		fmt.Printf("K2= %x\n",  k2)
		fmt.Printf("Sb= %x\n",  Sb)
		fmt.Printf("S2= %x\n\n",  S2)

	}
}
```

**Comment by pedroalbanese** [comment]
Hey chenxu, what's the AEAD mode used with SM4 (OpenSSL just have CBC, CTR, etc)?
