### ISSUE TITLE
Bug exporting Privatekey to Hex

### ISSUE THREAD

**Issue by pedroalbanese** [tjfoc/gmsm#124]
Greetings!

I need help to understand a bug in exporting keys to hex.. I believe it is related to the conversion function as it also occurs with other curves, not just SM2.

The following example generates keypair in hex but it fails once every ten attempts at least. It happens that 63-character keys are not rarely generated:

```go
	var err error
	var priv *sm2.PrivateKey
	priv, err = sm2.GenerateKey(rand.Reader)
	if err != nil {
		log.Fatal(err)
	}
	if len(WritePrivateKeyToHex(priv)) != 64 {
		log.Fatal("Private key too short!")
		os.Exit(1)
	}
	pub := &priv.PublicKey

	fmt.Println("Private= " + WritePrivateKeyToHex(priv))
	fmt.Println("Public= " + WritePublicKeyToHex(pub))
	os.Exit(0)
```

Does anyone know what this is due to? Thanks!

**Comment by pedroalbanese** [comment]
The following example generates a 63-character Privatekey:

```go
package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"github.com/tjfoc/gmsm/sm3"
	"golang.org/x/crypto/pbkdf2"
	"log"
)

func main() {
	flag.Parse()
	prvRaw := pbkdf2.Key([]byte("ops"), []byte(""), 1, 32, sm3.New)
	priv, err := ReadPrivateKeyFromHex(hex.EncodeToString(prvRaw))
	if err != nil {
		log.Fatal(err)
	}
	pub := &priv.PublicKey

	fmt.Println("Private= " + WritePrivateKeyToHex(priv))
	fmt.Println("Public= " + WritePublicKeyToHex(pub))
}
```

**Comment by czdsdo** [comment]
Private key consists of only one number,so there is no 64-bit limit on the length of the private key.
The public key consists of two 32-bit  numbers, each number will  pad zero  in order to parse it accurately.
You can pad zeros in front of private key if you want have a 64-bit limit .

**Comment by pedroalbanese** [comment]
How to pad zeros in front of private key? 

Thanks!

**Comment by czdsdo** [comment]
refer to x509/utils.go writePubkeyToHex
      ` d:= key.D.Bytes()
	if n := len(d; n <64 {
		d = append(zeroByteSlice()[:64-n], d...)
	}
	c := []byte{}
	c = append(c, d...)
	return hex.EncodeToString(c)`

**Comment by pedroalbanese** [comment]
Thank You very much!
