### ISSUE TITLE
可否添加 sm3.Size sm3.BlockSize 包常量

### ISSUE THREAD

**Issue by xuyang2** [tjfoc/gmsm#142]
可否给 `package sm3` 添加包常量
```
const Size = 32
const BlockSize = 64
```

见：

https://github.com/tjfoc/gmsm/blob/02e00ad77028ae97d4d768079d271adb858d59e4/sm3/sm3.go#L189-L196

https://github.com/tjfoc/gmsm/blob/02e00ad77028ae97d4d768079d271adb858d59e4/sm4/sm4.go#L28

和标准库：
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/sha512/sha512.go#L28-L42
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/sha256/sha256.go#L21-L28
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/md5/md5.go#L24-L28

**Comment by czdsdo** [comment]
SM3结构体里有常量的声明了。没有再全局声明的必要了。哈希算法类型的长度固定。使用的时候也不会用到这长度的声明吧。

**Comment by xuyang2** [comment]
@czdsdo 

导出常量可以方便使用，比如可以
```
b:= a[0:sm3.Size]
```

而不用
```
var h sm3.SM3
a:= b[0:h.Size()]
```
