### ISSUE TITLE
gm for fabric-go-sdk

### ISSUE THREAD

**Issue by poundscaoying** [tjfoc/gmsm#16]
is there any resource for fabric-go-sdk to use fabric-gm ? thanks

**Comment by poundscaoying** [comment]
sdk部分需要做国密算法的替换么，是不是直接给SDK配置国密证书就可以，谢谢

**Comment by nnsgmsone** [comment]
你可以替换，那个gmsm的接口和标准的ecdsa实际上一样的。

**Comment by poundscaoying** [comment]
还有个问题麻烦问您一下，就是国密fabric里的orderer支持kafka模式么
