### ISSUE TITLE
我遇到了一个go去改写java的需求，里面用到了SM2。原本是java bouncy castle实现的。现在换成go的一直实现不了，可以指导一下吗

### ISSUE THREAD

**Issue by leapig** [tjfoc/gmsm#164]
我目前对接的一个java的项目，他们给的公钥是用的java bouncy castle的包去压缩后给过来的，需要自己去实现publicKey
	d, _ := hex.DecodeString(“publickey”)
	c := sm2.P256Sm2()
	PublicKey := &sm2.PublicKey{Curve: c, X: new(big.Int).SetBytes(d[1:33]), Y: new(big.Int).SetBytes(d[33:])} //这里压缩后的公钥头是0x04，在java bouncy castle的解压里面可以看出来第一位是标志位，所以去掉，从第二位开始。不知道能不能帮到你。x、y取32位是因为压缩成65位的，所以去掉1位除以2，分别给x、y就可以了。

_Originally posted by @cage1993 in https://github.com/tjfoc/gmsm/issues/79#issuecomment-743159076_

**Comment by YesLiu** [comment]
看这个https://github.com/tjfoc/gmsm/issues/100

    func generateSM2PublicKey(publicKeyStr string) *sm2.PublicKey {
    
	    publicKeyStr = strings.TrimLeft(strings.TrimPrefix(publicKeyStr, "04"), "0")
	    x, _ := new(big.Int).SetString(publicKeyStr[0:64], 16)
	    y, _ := new(big.Int).SetString(publicKeyStr[64:], 16)
    
	    return &sm2.PublicKey{
		    Curve: sm2.P256Sm2(),
		    X:     x,
		    Y:     y,
	    }
    }
