### ISSUE TITLE
希望可以有tls的使用样例，以及一些问题反馈

### ISSUE THREAD

**Issue by Laurent-Chen** [tjfoc/gmsm#194]
1.客户端、服务器同时使用gmtls.GMTLS_SM2_WITH_SM1_SM3使用时报handshake error : tls: no cipher suite supported by both client and server，加密套件不适配。
2.GMTLS_ECDHE_SM2_WITH_SM4_SM3会进入gm_key_agreement.go第71行的panic

**Comment by emmansun** [comment]
你可以尝试使用https://github.com/Trisia/gotlcp

**Comment by Laurent-Chen** [comment]
感谢解答
