### ISSUE TITLE
没有userId参数吗？

### ISSUE THREAD

**Issue by wtysksk** [tjfoc/gmsm#20]
msg, _ := hex.DecodeString("39393939313131313132333431326464646461616132323232323232323232323232323232323232323232323231313131")
	sign, _ := hex.DecodeString("B573007F61A773626A1229936B8ACAE29228E1A343D8156472194DBBD41AC450E178DC876BEAA75922CBFB1D92C102391A87B84AE83202C28B09EADBDB8E6C8A")
	pubkeyByte, _ := hex.DecodeString("0B085AA0473B0AD429189263B52D7A05C998CC5E7523F9E6F17DCCC4F9BCD4EEDBAB204B8F8FE17A2D1E70D1B23FC1BB24B58768F77CF10E372AD930A9ACF3ED")
	pubkey, _ := sm2.ParseSm2PublicKey(pubkeyByte)
	ok := pubkey.Verify(msg, sign)
	if ok {
		fmt.Println("ok\n")
	} else {
		fmt.Print("fail\n")
	}
是不是没有用上国密推荐的userId参数  1234567812345678 ？
公钥验签是上述代码这样做的吗？我用已经验证过的JAVA代码生成的数据用上述代码做验签，都不行（不管JAVA代码生成的数据有没有用上userId做哈希）

**Comment by zcc0721** [comment]
他实现的国密算法是正确的，你要注意的是他实现的只是推荐的曲线参数构造的函数。采用的参数标准遵从GB/T 32918.5-2017标准推荐的p, a, b, n, xG, yG。你用Java代码生成的数据验签要保证采用的参数满足这个标准推荐的参数。

你可以查看https://github.com/Bytom/bytom/blob/opsm2/crypto/sm2/sm2_verify_test.go的测试函数。运行一下，上面的测试数据遵从国标。运行结果通过。git clone 一下这个库，然后go test 这个文件就知道了。

**Comment by nnsgmsone** [comment]
你可以用sm2Sign这个函数，这个函数可以传入uid参数。默认的sign函数不用uid这个东西的。。
