### ISSUE TITLE
公钥压缩算法实现没有遵从国密标准

### ISSUE THREAD

**Issue by zcc0721** [tjfoc/gmsm#23]
根据国密标准[GB/T 32918.1-2016](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=3EE2FD47B962578070541ED468497C5B)中的第4.2.9的描述：
![image](https://user-images.githubusercontent.com/17916496/43814332-58956576-9afc-11e8-98c8-c9e7383cc9e6.png)

公钥压缩字节串格式首字节应该是0x02或是0x03，具体取决于特殊比特位的值是0还是1。但是在我测试的时候却发现实现过程中首字节貌似是0x00和0x01，没有一个转换的过程。这一点与国密标准相悖。望请改正。

如果是我测试或者理解错误，请在issue下面回复一下，别直接就关闭issue，上次给你们提一个pr，你们直接关闭，我以为是自己理解错误，谁知道你们后来改了过来，我很郁闷。

感谢你们的开源项目，比原链项目中的国密算法部分采用了你们的代码，在此感谢！

**Comment by nnsgmsone** [comment]
设P=(x P , y P )是定义在F p 上椭圆曲线E:y 2 = x 3 + ax + b上的一个点,ỹ P 为y P 的最右边的一个比特,
则点P可由x P 和比特ỹ P 表示。
由x P 和ỹ P 恢复y P 的方法如下:
a) 计算域元素α=(x P 3 + ax P + b) modp;
b) 计算α modp的平方根β(参见附录B.1.4),若输出是“不存在平方根”,则报错;
c) 若β的最右边比特等于ỹ P ,则置y P =β;否则置y P = p − β。
我看的是这个。。。莫非我们看的标准不是同一个吗？？

**Comment by zcc0721** [comment]
我们看的是伊特标准，你摘录的应该是GB/T 32918.1-2016 的A5.2 节的内容。但是这节的内容标题是：F_p上椭圆曲线点的压缩与解压缩方法。而4.2.9的描述中主要是点到字节串的转换，而sm2.go的实现部分是：

```go
func Compress(a *PublicKey) []byte {
	buf := []byte{}
	yp := getLastBit(a.Y)
	buf = append(buf, a.X.Bytes()...)
	if n := len(a.X.Bytes()); n < 32 {
		buf = append(zeroByteSlice[:(32-n)], buf...)
	}
	buf = append([]byte{byte(yp)}, buf...)
	return buf
}
```

该函数输出是字节串，因此我认为应该以02或03开头。

**Comment by zcc0721** [comment]
Compress函数输入是一个点，那么输出既然是字节串，那么也应该加上02或03

**Comment by nnsgmsone** [comment]
那我空了看看吧。。。哈哈，可能看漏了。。。不过我看商业的实现貌似不是bit是byte。。这个是什么情况呢。。。兄台你们取的是Bit还是byte

**Comment by zcc0721** [comment]
byte居多

**Comment by nnsgmsone** [comment]
好吧。。那我空了改一下。。。不过最近很忙

**Comment by zcc0721** [comment]
是的，但是比原链和巴比特其实属于公司的不同的产品线

**Comment by nnsgmsone** [comment]
哦

**Comment by liwangqiang** [comment]
mmm, 看上去这个 issue 还在..
