### ISSUE TITLE
私钥长度是32字节，为什么将b设置为40字节？

### ISSUE THREAD

**Issue by zcc0721** [tjfoc/gmsm#24]
https://github.com/tjfoc/gmsm/blob/0b26aafa7604a3cd63d76facfb62dc7885c068fa/sm2/sm2.go#L137~L145
```go
func randFieldElement(c elliptic.Curve, rand io.Reader) (k *big.Int, err error) {
	params := c.Params()
	b := make([]byte, params.BitSize/8+8)
	_, err = io.ReadFull(rand, b)
	if err != nil {
		return
	}
	k = new(big.Int).SetBytes(b)
	n := new(big.Int).Sub(params.N, one)
	k.Mod(k, n)
	k.Add(k, one)
	return
}
```

这样的话私钥k的值其实就是40字节长度的整数。这个用意是什么？我看国密标准里没有此项表述。

**Comment by zcc0721** [comment]
我知道到后来还是要取余的，但是这个意义？因为取余和不取余其分布均为均匀分布的。

**Comment by GoldSaintEagle** [comment]
> 我知道到后来还是要取余的，但是这个意义？因为取余和不取余其分布均为均匀分布的。

首先，这段代码是参考ecdsa的实现，ecdsa也的确这么做了。
其次，多几位是为了均匀分布。比如模n为14，你不能生成4 bits的随机数（0～15），如果这样的话，取模之后，0和1的概率是其他数的两倍。最优且均匀的方法是生成[14, 16]=2*7*8=112个随机数。然而这个要求往往对于rand和取模来说过于苛刻，于是就有了`params.BitSize/8+8`位的随机数，基本均匀，且生成之后的数不会过大，影响计算效率。
