### ISSUE TITLE
oidSM2算法标识不对

### ISSUE THREAD

**Issue by sqtds** [tjfoc/gmsm#26]
oidSM2 = asn1.ObjectIdentifier{1, 2, 840, 10045, 2, 1}    这是ecdsa的

**Comment by sqtds** [comment]
gmsm/sm2/pkcs8.go下

**Comment by jovijovi** [comment]
@sqtds Is this a problem? 这个问题确认了吗？

**Comment by sqtds** [comment]
oid标识不对难道不是问题？

**Comment by GoldSaintEagle** [comment]
> oid标识不对难道不是问题？

其实这个oid表示的是id-ecPublicKey，然而，sm2 TMD没有一个叫id-sm2PublicKey的OID（难道非要逼我用sm9的这个OID？……真是X了狗）。所以，该项目用ec的国际标准中的oid也无可厚非，反正可以用过curve的oid来判断。不过，我自己的实现定义了新的id-sm2PublicKey的OID，是**1.2.156.10197.1.301**。当然，两种实现各有利弊，我的扩展性可能会低；该项目的可能会产生歧义（如果判断算法时候用了sm2的oid就挂了）

附上ec和sm，国际标准中的oid对比：
【EC    Curve OID】prime256v1：1 2 840 10045 3 1 7
【SM2 Curve OID】prime256v1：1 2 156 10197 1 301
【SHA256WithECDSA OID】ecdsa-with-SHA256：1 2 840 10045 4 3 2
【SM3WithSM2            OID】SM2Sign-with-SM3  ：1 2 156 10197 1 501
