### ISSUE TITLE
能否支持golang mod的语义化版本号

### ISSUE THREAD

**Issue by zcx2001** [tjfoc/gmsm#29]
在golang 1.12.1中通过go get的导入v1.2这个项目失败，能否支持golang mod的语义化版本号。
https://semver.org/lang/zh-CN/

**Comment by czdsdo** [comment]
你能fork项目来自定义mod的语义化版本.

**Comment by studyzy** [comment]
麻烦发布一个版本：
v1.2.0
不这么写的话，GO 11 module不支持。

**Comment by cr4zyvv** [comment]
建议修改下分支和版本号，建议统一用x.y.z样式的版本号，go module好像只认x.y.z
否则默认go module下，只能认1.0.1版本（x.y.z），不认1.2（x.y）
虽然可以手动修改或自己fork解决，但是很不方便

**Comment by GongShengzhi** [comment]
Fix go mod 支持
