### ISSUE TITLE
解析国密证书出错

### ISSUE THREAD

**Issue by zyrfree** [tjfoc/gmsm#38]
asn1: structure error: integer not minimally-encoded 
我解析sm2签名证书出现这个错误 是什么原因？调用rest, err := asn1.Unmarshal(asn1Data, &cert)

**Comment by GongShengzhi** [comment]
请问你的sm2签名证书是如何生成的？

**Comment by zyrfree** [comment]
问题已经解决了，谢谢



zyrfree@126.com
 
发件人： GongShengzhi
发送时间： 2019-12-25 17:14
收件人： tjfoc/gmsm
抄送： 苏伟; Author
主题： Re: [tjfoc/gmsm] 解析国密证书出错 (#38)
请问你的sm2签名证书是如何生成的？
