### ISSUE TITLE
tag命名不规范，go mod无法识别

### ISSUE THREAD

**Issue by zrynuaa** [tjfoc/gmsm#40]
go get github.com/tjfoc/gmsm@v1.2: no matching versions for query "v1.2"
go get github.com/tjfoc/gmsm@v1.2.0: github.com/tjfoc/gmsm@v1.2.0: invalid version: unknown revision v1.2.0

go mod 需要识别类似 v1.2.0 的tag

**Comment by GongShengzhi** [comment]
tag 已修改为v1.2.0
