### ISSUE TITLE
sm3 算法中update方法的nblocks参数是不是没用了

### ISSUE THREAD

**Issue by xcaptain** [tjfoc/gmsm#41]
https://github.com/tjfoc/gmsm/blob/71e91645d4e3bd374b9bd51217bda0eb4ee760ab/sm3/sm3.go#L66

在整个方法中找不到用到的地方

**Comment by czdsdo** [comment]
由于当时实现时有参考C实现 ，C中使用了指针，nblocks参数是用来确认数据的位置，GO实现中将指针移位放在了170行中Write方法中。没有放在update方法中。在update方法中该参数是没有用的。
