### ISSUE TITLE
sm4加解密问题

### ISSUE THREAD

**Issue by vager** [tjfoc/gmsm#46]
参考sm4_test.go中代码
https://github.com/tjfoc/gmsm/blob/867dc485371b4d1165d1f63faafa71fa031364b3/sm4/sm4_test.go#L25
当变量data换个值后,就失败了
```golang
func TestSm4(t *testing.T) {
	key := []byte("1234567890abcdef")
	fmt.Printf("key = %x\n", key)
	data := []byte("hello, world,,asdjkfhaksldfhjalskdfjhalsdfhj")
	fmt.Printf("data = %x\n", data)
	c, err := sm4.NewCipher(key)
	if err != nil {
		log.Fatal(err)
	}
	d0 := make([]byte, len(data))
	c.Encrypt(d0, data)
	fmt.Printf("d0 = %x\n", d0)
	d1 := make([]byte, len(data))
	c.Decrypt(d1, d0)
	fmt.Printf("d1 = %x\n", d1)

	t.Errorf("\n%x\n%x\n%x\n", data, d0, d1)
}
```
加密后后半部分数据全成0了
data=68656c6c6f2c20776f726c642c2c6173646a6b6668616b736c6466686a616c736b64666a68616c736466686a
d0=bd444d3e066e932409213856ec7010ff00000000000000000000000000000000000000000000000000000000
d1=68656c6c6f2c20776f726c642c2c617300000000000000000000000000000000000000000000000000000000

**Comment by czdsdo** [comment]
SM4加密解密仅适用于32位定长的原文。加密内容如果少于32位会报错，多于32位只会取其前16位数据。由于SM4设计是这样的所以会出现你这种情况。
通常操作是先将原文sm3哈希成16位hash值，然后进行sm4加密其hash值，解密后再验证其hash值是否与原文sm3哈希值相同。
