### ISSUE TITLE
 How do I distinguish between SM2 and ECDSA in the caller?

### ISSUE THREAD

**Issue by JulienGuo** [tjfoc/gmsm#5]
Why is SM2 treated as one of the ECDSA?

There is no difference between sm.PublicKey and ecdsa.PublicKey in memory structure.

**Comment by tjfoc** [comment]
SM2 is based on ECC. The code is support both SM2 and ECDSA.

case *ecdsa.PublicKey:
    pub, _ = x509Cert.PublicKey.(*ecdsa.PublicKey)
    switch pub.Curve {
    case sm2.P256Sm2():
      ...
    default:
       priv, ok := cert.PrivateKey.(*ecdsa.PrivateKey)
