### ISSUE TITLE
能否增加p12证书解析码

### ISSUE THREAD

**Issue by wang4424** [tjfoc/gmsm#57]

**Comment by czdsdo** [comment]
由于目前没有关于sm2的p12证书格式标准，我们在下个版本会暂加入按照RSA 的P12证书格式实现的P12证书解析跟生成。

**Comment by wang4424** [comment]
谢谢解答



在 2020-05-14 14:54:58，"chenxu" <notifications@github.com> 写道：

由于目前没有关于sm2的p12证书格式标准，我们在下个版本会暂加入按照RSA 的P12证书格式实现的P12证书解析跟生成。
