### ISSUE TITLE
SM2 Signature Algorithm in x509 certificate should not be the same as ECDSA

### ISSUE THREAD

**Issue by warm3snow** [tjfoc/gmsm#6]
I found the sm2 use the signature algorithm oid of ecdsa, which is 
`oidSignatureECDSAWithSHA256 = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 2}`.
When i use gmssl to parse the certificate created by sm2/x509.go, I got something like
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
             (Negative)01
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: O = TEST, CN = test.example.com, GN = Gopher, C = NL
        Validity
            Not Before: Jan  1 00:16:40 1970 GMT
            Not After : Jan  2 03:46:40 1970 GMT
        Subject: O = TEST, CN = test.example.com, GN = Gopher, C = NL
```
Note: the certificate is created by `go test` in gmsm/sm2
In fact, sm2 has its own signature algorithm. 

**对象标识符	名称	       OID**
- rsaEncryption	RSA算法标识	1.2.840.113549.1.1.1
- sha1withRSAEncryption	SHA1的RSA签名	1.2.840.113549.1.1.5
- ECC	ECC算法标识	1.2.840.10045.2.1
- SM2	SM2算法标识	1.2.156.10197.1.301
- SM3WithSM2	SM3的SM2签名	1.2.156.10197.1.501
- sha1withSM2	SHA1的SM2签名	1.2.156.10197.1.502
- sha256withSM2	SHA256的SM2签名	1.2.156.10197.1.503
- sm3withRSAEncryption	SM3的RSA签名	1.2.156.10197.1.504
- commonName	主体名	2.5.4.3
- emailAddress	邮箱	1.2.840.113549.1.9.1
- cRLDistributionPoints	CRL分发点	2.5.29.31
- extKeyUsage	扩展密钥用法	2.5.29.37
- subjectAltName	使用者备用名称	2.5.29.17
- CP	证书策略	2.5.29.32
- clientAuth	客户端认证	1.3.6.1.5.5.7.3.2

I have a pull/request to fix it.  And parsing the certificate created by the new code, I can get
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
             (Negative)01
    Signature Algorithm: sm2sign-with-sha256
        Issuer: O = TEST, CN = test.example.com, GN = Gopher, C = NL
        Validity
            Not Before: Jan  1 00:16:40 1970 GMT
            Not After : Jan  2 03:46:40 1970 GMT
        Subject: O = TEST, CN = test.example.com, GN = Gopher, C = NL
```
--------------------------------end line--------------------------
`xyz:~/gopath/src/github.com/tjfoc/gmsm/sm2$ gmssl x509 -text -noout -in cert.pem`

**Comment by tjfoc** [comment]
yes. found this issue. improving in progress. will merge updated version soon.
