### ISSUE TITLE
SigtoPub

### ISSUE THREAD

**Issue by caoliangccut20121192** [tjfoc/gmsm#60]
国密签名和ECDSA签名都需要临时公钥，ecdsa 签名是r=x1mod/n,国密的r=(h+x1)modn,ecdsa可以恢复公钥，国密理论上是不是也可以推导啊

**Comment by czdsdo** [comment]
[s]G +[t]P的结果可以推导出等于[k]G

**Comment by czdsdo** [comment]
t=(r+s) mod n

**Comment by czdsdo** [comment]
t=(r+s) mod n
r-h=x1
[k]G=(x1,y1)
因为[s]G +[t]P=[k]G,所以[t]P=[k]G-[s]G。
t,[k]G-[s]G可求，但椭圆曲线实现上只有多倍点的乘法，没有除法，是求不出公钥P来的。
s= ((1+d)-1 * (k-r*d)) mod n，s的计算方式跟ecdsa中不一样，是不能从s中计算单独得到公钥P=dG的，只能计算出临时公钥kG。

**Comment by caoliangccut20121192** [comment]
那我两边都乘t的逆元可以吗
