### ISSUE TITLE
怎么与Java的代码对接？

### ISSUE THREAD

**Issue by Gordon-H** [tjfoc/gmsm#61]
Java端我用的bouncycastle库的实现，Golang用的事gmsm的1.1.1版本，测试后发现SM3的结果是一致的，但用SM2签名后的信息无法互通，也就是说对某个信息用公钥加密后，在另一端无法验证。另外我发现gosm用公钥对同个信息签名，每次签名的结果是一样的；而在bouncycastle库的实现中，每次签名的结果是不一样的，好像加入了随机数。

是不是算法的实现细节有差异？有否给个解决思路？

**Comment by wenyuan138** [comment]
同样的疑问，java端bouncycastle库的sm2签名之后，在gmsm无法验证

**Comment by wangzheyuan** [comment]
我用gmsm 1.2.4能成功验证bouncycastle的sm2签名，用gmsm 1.3.1则验证失败。

**Comment by czdsdo** [comment]
> 
> 
> 我用gmsm 1.2.4能成功验证bouncycastle的sm2签名，用gmsm 1.3.1则验证失败。

你核对一下java那边sm2签名使用的uid项。1.2.4能验过uid为空或为默认值的签名，1.3.1只能验证uid为默认值时的签名。按照标准uid应使用默认值。

**Comment by czdsdo** [comment]
每次签名返回的签名值应该是不相同的，你可以尝试使用更高版本的。签名验证不通过多半是uid不一致导致的，你可以确认一下两边是否使用相同的uid

**Comment by wangzheyuan** [comment]
> > 我用gmsm 1.2.4能成功验证bouncycastle的sm2签名，用gmsm 1.3.1则验证失败。
> 
> 你核对一下java那边sm2签名使用的uid项。1.2.4能验过uid为空或为默认值的签名，1.3.1只能验证uid为默认值时的签名。按照标准uid应使用默认值。

将uid修改为默认值，1.3.1的sm2.Sm2Verify可以成功验证的bouncycastle的sm2签名。但使用CheckSignature仍然验证失败，在CheckSignature中Sm2Verify使用的uid项是空，不是默认值。
