### ISSUE TITLE
在gmsm/sm2/x509.go main分支func checkSignature的问题

### ISSUE THREAD

**Issue by bolenzhang** [tjfoc/gmsm#63]
如题 x509.go 998 行，switch pub := publicKey.(type) 中为什么没有*sm2.PulicKey的case？
但是在其他地方，如func signingParamsForPublicKey中switch pub := publicKey.(type)，却有*sm2.PulicKey的case。

请问这个是基于什么特殊原因考虑的吗？

**Comment by czdsdo** [comment]
998 行中的方法传入的是crypto.PublicKey 继承这个的公钥，sm2公钥归属ecdsa的公钥。
其他方法中的公钥为interface{}.

**Comment by czdsdo** [comment]
998行的方法是原标准库x509里的方法，传入的公钥为crypto.PublicKey。我们在实现中新增了sm2公钥，没有修改传入参数的类型。其他方法为当时开发人员自己实现的。
