### ISSUE TITLE
sm2 PrivateKey.Sign 传入的随机源无效

### ISSUE THREAD

**Issue by zhangfz** [tjfoc/gmsm#64]
在 PrivateKey.Sign中调用了Sm2Sign 此过程中传入随机源被丢弃。此处应考虑把随机源传递到运算中。因为在工程中有可能不用go语言默认的随机源。（代码 sm2.go  80行）

**Comment by ldlqdsdcn** [comment]
稳定性貌似比椭圆曲线差不少

**Comment by czdsdo** [comment]
由于涉及到引用的方法传入参数修改，后续的版本发布后可能不再兼容之前的签名操作。在短期发布的版本是不会加入随机源，在后续大版本更新时才会加入。

**Comment by zhangfz** [comment]
期待大版本更新
