### ISSUE TITLE
SM4 EncryptBlock/DecryptBlock加密前结果和解密后的结果不一致

### ISSUE THREAD

**Issue by manxiaqu** [tjfoc/gmsm#72]
```golang
func TestSm4Block(t *testing.T) {
	key := []byte("1234567890abcdef")
	data := []byte{0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10}

	dst := make([]byte, 16)
	EncryptBlock(key, dst, data)

	dry := make([]byte, 16)
	DecryptBlock(key, dry, dst)

	assert.True(t, bytes.Equal(dst, dry))
}
```
上述代码无法通过测试，`sm4_test.go`中的TestSM4可以通过测试，两者好像只有调用cryptBlock时有些许不同
* 使用Sm4Cipher:  cryptBlock(c.subkeys, c.block1, c.block2, dst, src, true)中的c.block1, c.block2在一开始已经构建好了，在加密后，值可能改变，并应用到了之后的解密中。
* EncryptBlock/DecryptBlock: 每次均创建空的字节数组

是否因为上述原因导致无法解密出正确的结果？

**Comment by zltl** [comment]
修改你的测试函数： `assert.True(t, bytes.Equal(data, dry))`

**Comment by manxiaqu** [comment]
我的错，没注意到比较错了相应的数据。
