### ISSUE TITLE
sm2/x509中ParsePKIXPublicKey与MarshalPKIXPublicKey不是一一对应的

### ISSUE THREAD

**Issue by manxiaqu** [tjfoc/gmsm#73]
https://github.com/tjfoc/gmsm/blob/master/sm2/x509.go#L130 中，MarshalPKIXPublicKey可以对sm2.PublicKey进行序列化，但是在序列化之后调用ParsePKIXPublicKey对结果进行反序列化，无法得到sm2.PublicKey对象:
```golang
func TestMarshal(t *testing.T) {
	priv, err := GenerateKey() // 生成密钥对
	assert.Nil(t, err)

	pub := priv.Public()

	raw, err := MarshalPKIXPublicKey(pub)
	assert.Nil(t, err)

	parsePub, err := ParsePKIXPublicKey(raw)
	assert.Nil(t, err)

	oriType := fmt.Sprintf("%v", reflect.TypeOf(pub))
	actualType := fmt.Sprintf("%v", reflect.TypeOf(parsePub))

	// expected: "*sm2.PublicKey"
	// actual  : "*ecdsa.PublicKey"
	assert.Equal(t, oriType, actualType)
}
```
运行上述代码可以发现，对sm2.PublicKey序列化之后，在反序列化，得到的结果是ecdsa.PublickKey; 建议在ParsePKIXPublicKey中增加对sm2.PublicKey的处理，因为MarshalPKIXPublicKey中可以对sm2.PublicKey序列号。

**Comment by czdsdo** [comment]
考虑到兼容证书采取其他算法，序列化与反序列化出是通用的公钥接口。按照你的想法应该是使用

`ParseSm2PublicKey，MarshalSm2PublicKey`两个序列化与反序列化函数
