### ISSUE TITLE
一些实现不符合国家标准

### ISSUE THREAD

**Issue by zhangzhanli** [tjfoc/gmsm#74]
本人最近正在做可信区块链评测，不知道你们的通没通过。
目前没看完你们的代码，只看到30%左右，发现有几个问题不符合标准，烦请对着GB/T 32918-1~5 GM0003再确认一下。

1）sm2.go : 164   func GenerateKey() (*PrivateKey, error) 函数中，d 的取值范围应为 [1,n-2], 你们的实现明显有n-1, 不知在计算s 时 (d+1) ^ -1 会出什么结果， 理论上是找不到逆的，实际效果没试
2）sm2.go : 390 func ZA(pub *PublicKey, uid []byte) ([]byte, error) 函数中，yBuf的位数不对，Fq 为素数域，【q/8】向上取整，没看到有
if n := len(yBuf); n < 32 {
		yBuf = append(zeroByteSlice()[:32-n], yBuf...)
	}
3）性能问题。使用你们的sm2签名并验签 16k 次，所花时间为1min3s (i5-6* U), 而同样强度的P256仅需2.9s不到，不足你们的零头，不知道你们后续有没优化的工作计划，还是开源和生产上使用的两套？

**Comment by bensonfx** [comment]
@zhangzhanli 测试了一下签名验签，
**环境**：i7-8700t,  
```bash
go test -cpu 1,12 test.bench Sm2.*
```
![image](https://user-images.githubusercontent.com/3302960/89174720-e6236700-d5b8-11ea-8311-5b84c2788730.png)


结论：
1. 性能上比你测试的差不多, 只是用了一个核，
2. 使用并发进行benchmark， 速度差不多提到接近你提到的P256的速度。

**Comment by bensonfx** [comment]
分析了一下pprof， 发现主要耗时都在`sm2P256ReduceDegree`调用上

**Comment by czdsdo** [comment]
谢谢您 的代码审查，确实发现了这部分内容与标准不符，会修复这部分内容。sm2P256ReduceDegree性能方面在标准库P256上优化过一次，后续会考虑在汇编这层优化性能。
