### ISSUE TITLE
如何从字符串中读取公钥私钥

### ISSUE THREAD

**Issue by pingyuan7** [tjfoc/gmsm#77]
如何从字符串中读取公钥私钥。
如何从XY坐标生成公钥

**Comment by royye62** [comment]
```golang
pubKeyStr="XXXX"  // length 128 hex string
x, _ := new(big.Int).SetString(pubKeyStr[:64], 16)
y, _ := new(big.Int).SetString(pubKeyStr[64:], 16)
pub := &sm2.PublicKey{
	Curve: sm2.P256Sm2(),
	X:     x,
	Y:     y,
}
```

**Comment by czdsdo** [comment]
公钥长度你注意下，第一个字节可能是标识 ，标识04表示未压缩的公钥格式。XY坐标各32bytes共64bytes.若有标识则为65bytes.后续取坐标值往后移一位
x, _ := new(big.Int).SetString(pubKeyStr[:32], 16)
y, _ := new(big.Int).SetString(pubKeyStr[32:64], 16)
pub := &sm2.PublicKey{
	Curve: sm2.P256Sm2(),
	X:     x,
	Y:     y,
}
