### ISSUE TITLE
branch [dev-fabric] 迁移到TWGC

### ISSUE THREAD

**Issue by davidkhala** [tjfoc/gmsm#78]
@czdsdo 陈序，我观察到最近的新commit都只在
https://github.com/Hyperledger-TWGC/tjfoc-gm这里面
而dev-fabric 暂时没有commit ahead
是否可以考虑deprecate这个仓库的dev-fabric branch？

**Comment by czdsdo** [comment]
OK，后续commit直接放在tjfoc-gm中

**Comment by davidkhala** [comment]
我们可以在dev-fabric的readme上做一个分流Notice么？
比如说请前往本仓库的master branch 或者 Hyperledger-twgc
