### ISSUE TITLE
和java实现的国密无法兼容

### ISSUE THREAD

**Issue by Eggsyz** [tjfoc/gmsm#79]
你好，我们通过gmsm可以对一个内容进行签名验签，但是通过gmsm签名，java实现的国密验签失败，在排查过程中，发现了这个参数：7ffffffd80000002fffffffe000000017ffffffe800000037ffffffc80000002。请问一个该参数意义是什么？谢谢

**Comment by zhiMcoding** [comment]
解决了吗？同样的问题

**Comment by zhiMcoding** [comment]
解决了吗？

**Comment by cage1993** [comment]
我目前对接的一个java的项目，他们给的公钥是用的java bouncy castle的包去压缩后给过来的，需要自己去实现publicKey
	d, _ := hex.DecodeString(“publickey”)
	c := sm2.P256Sm2()
	yztSm2PublicKey = &sm2.PublicKey{Curve: c, X: new(big.Int).SetBytes(d[1:33]), Y: new(big.Int).SetBytes(d[33:])} //这里压缩后的公钥头是0x04，在java bouncy castle的解压里面可以看出来第一位是标志位，所以去掉，从第二位开始。不知道能不能帮到你。
