### ISSUE TITLE
sm4 test

### ISSUE THREAD

**Issue by QwertyJack** [tjfoc/gmsm#8]
sm4
小白。

按我的理解，`data`是原始数据，`d0`是加密`data`的结果，`d1`是解密`d0`的结果。那么`d1`跟`data`是不是应该一样？

```
$ go test
key = [49 50 51 52 53 54 55 56 57 48 97 98 99 100 101 102]
key = [49 50 51 52 53 54 55 56 57 48 97 98 99 100 101 102]
data = 0123456789abcdeffedcba9876543210
d0 = 17e653832de37333d216c6be7cf13e6e
d1 = fcc8ab0fb273e1775152840cbd533ebd
PASS
ok      /git/gmsm/sm4       0.007s
```

**Comment by nnsgmsone** [comment]
d1和data应该一样的。那个上次pull弄错了顺序，现在代码已经可以正常工作了。谢谢

**Comment by nnsgmsone** [comment]
谢谢，那个确实master的sm4有bug，我在从develop merge的时候操作失误导致的(冲突的时候我保留了master的代码，实际上应该用develop的代码覆盖master的代码)。。。那个现在master的sm4的bug已经修复，多谢哦。你的理解没有任何问题

**Comment by QwertyJack** [comment]
👍

**Comment by QwertyJack** [comment]
I also am interested in your projects. I will be happy if u can leave me your email address or QQ.

**Comment by nnsgmsone** [comment]
nnsmgsone@gmail.com, i don't use qq..may be weixin mc_nns
