### ISSUE TITLE
压测发现sm2的加密性能和ecc差20倍，是我使用的问题吗

### ISSUE THREAD

**Issue by tututt** [tjfoc/gmsm#80]

**Comment by tututt** [comment]
同样加密“hello world”,  在mac 1.7 GHz 四核Intel Core i7 机器上，ecc使用p256 curve
sm2: 1421542 ns/op
ecc: 68734 ns/op
麻烦解释一下，谢谢

**Comment by shengzhi** [comment]
标准包中ecc针对不同的cpu架构和型号做了针对性的汇编优化，用到了AVX或AVX2的指令，所以性能要高出很多

**Comment by tututt** [comment]
那当前项目有没有计划针对这个进行优化呢？有的话时间节点是什么？

**Comment by mmzhi** [comment]
要搞汇编优化就复杂啦
