### ISSUE TITLE
sm4

### ISSUE THREAD

**Issue by QwertyJack** [tjfoc/gmsm#9]
两个问题：
1. 怎么设置盐(salt)？
2. 为什么要求`key`长度和`BlockSize`一样？

**Comment by nnsgmsone** [comment]
1. salt要自己实现，网上随便找个例子就好(gmsm提供的仅仅都是标准库提供的接口)
2. sm4的密钥长度和分组长度的要求都是128比特。。你可以看具体的算法描述

**Comment by QwertyJack** [comment]
明白了。
主要是对比 gmssl 结果不一致。
感谢！

**Comment by nnsgmsone** [comment]
多谢哦，兄台
 
 
------------------ Original ------------------
From: "jack"; 
Date: 2017年10月16日(星期一) 中午1:26
To: "tjfoc/gmsm"; 
Cc: "nnsgmsone"; "Comment"; 
Subject: Re: [tjfoc/gmsm] sm4 (#9)

 

明白了。
 主要是对比 gmssl 结果不一致。
 感谢！
