### ISSUE TITLE
sm4-gcm测试

### ISSUE THREAD

**Issue by tutorguai** [tjfoc/gmsm#93]
你好，我在做sm4-gcm测试的时候发现以下的问题，
1.传入data在大于或者小于16位时，全都报错，是因为当前实现的sm4-gcm算法里未支持分组吗？
2.在16位可加密出来的场景下，使用java Cipher+bouncycastle得到的结果多出了 16位MAC(数据位的加密是正确的)，但是当前的 go sm4-gcm算法中好像没有对应的实现，目前的sm4-gcm功能目前还不够完善吗，还是我使用的问题。

**Comment by czdsdo** [comment]
sm4-gcm这目前实现里没有做数据分组，所以会出现以上现象。目前的sm4-gcm功能实现目前还不够完善，后续优化。该模式的加密没有放在国标里，未经完善跟详细测试，不建议放在生产环境下使用。
